// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         someString: "someString",
 *         someInt: 1
 *     }
 */
export interface SendInlinedRequest {
    someString: string;
    someInt: number;
}
