/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../core/index.js";

export interface UploadSingleDocument {
    documentFile: core.file.Uploadable.FileLike;
}
