// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

export interface UploadMultipleDocumentsAndFields {
    documentFile1: core.file.Uploadable;
    documentFile2: core.file.Uploadable;
    documentFiles: core.file.Uploadable[];
    someString: string;
    someInteger: number;
    someBoolean: boolean;
}
