/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "../../../../../core/index.js";

export interface UploadListOfDocuments {
    documentFile1: core.file.Uploadable.FileLike;
    documentFile2: core.file.Uploadable.FileLike;
    documentFiles: core.file.Uploadable.FileLike[];
}
