// This file was auto-generated by Fern from our API Definition.

import { SeedApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Service", () => {
    test("simple", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ environment: server.baseUrl });

        server.mockEndpoint().post("/snippet").respondWith().statusCode(200).build();

        const response = await client.service.simple();
        expect(response).toEqual(undefined);
    });

    test("sendInlinedRequest", async () => {
        const server = mockServerPool.createServer();
        const client = new SeedApiClient({ environment: server.baseUrl });
        const rawRequestBody = { someString: "someString", someInt: 1 };

        server.mockEndpoint().post("/inlined-request").jsonBody(rawRequestBody).respondWith().statusCode(200).build();

        const response = await client.service.sendInlinedRequest({
            someString: "someString",
            someInt: 1,
        });
        expect(response).toEqual(undefined);
    });
});
