# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Account,
        AccountList,
        Address,
        BadLiteral1,
        BadLiteral2,
        BadLiteral3,
        BadLiteral4,
        BadLiteral5,
        BadLiteral6,
        BadLiteral7,
        BadLiteral8,
        Circle,
        Country,
        DocumentPath,
        EmeraldColor,
        EnumWithBadValues,
        Extensive,
        GreenColor,
        IsOpen,
        Project,
        Shape,
        Shape_Circle,
        Shape_Square,
        Shape_Triangle,
        Square,
        Triangle,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "Account": ".types",
    "AccountList": ".types",
    "Address": ".types",
    "BadLiteral1": ".types",
    "BadLiteral2": ".types",
    "BadLiteral3": ".types",
    "BadLiteral4": ".types",
    "BadLiteral5": ".types",
    "BadLiteral6": ".types",
    "BadLiteral7": ".types",
    "BadLiteral8": ".types",
    "Circle": ".types",
    "Country": ".types",
    "DocumentPath": ".types",
    "EmeraldColor": ".types",
    "EnumWithBadValues": ".types",
    "Extensive": ".types",
    "GreenColor": ".types",
    "IsOpen": ".types",
    "Project": ".types",
    "Shape": ".types",
    "Shape_Circle": ".types",
    "Shape_Square": ".types",
    "Shape_Triangle": ".types",
    "Square": ".types",
    "Triangle": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Account",
    "AccountList",
    "Address",
    "BadLiteral1",
    "BadLiteral2",
    "BadLiteral3",
    "BadLiteral4",
    "BadLiteral5",
    "BadLiteral6",
    "BadLiteral7",
    "BadLiteral8",
    "Circle",
    "Country",
    "DocumentPath",
    "EmeraldColor",
    "EnumWithBadValues",
    "Extensive",
    "GreenColor",
    "IsOpen",
    "Project",
    "Shape",
    "Shape_Circle",
    "Shape_Square",
    "Shape_Triangle",
    "Square",
    "Triangle",
]
