// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../index.js";

export interface Account {
    address_type: "country";
    name: string;
    is_open: boolean;
    country: SeedApi.Country;
}
