// This file was auto-generated by Fern from our API Definition.

export const EnumWithBadValues = {
    BadValue1: "badValue1",
    BadValue2: "badValue2",
    BadValue3: "badValue3",
} as const;
export type EnumWithBadValues = (typeof EnumWithBadValues)[keyof typeof EnumWithBadValues];
