/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type EnumWithBadValues = "badValue1" | "badValue2" | "badValue3";
export const EnumWithBadValues = {
    BadValue1: "badValue1",
    BadValue2: "badValue2",
    BadValue3: "badValue3",
} as const;
