// This file was auto-generated by Fern from our API Definition.

import type * as SeedApi from "../../../index.js";

export type Shape = SeedApi.Shape.Triangle | SeedApi.Shape.Square | SeedApi.Shape.Circle;

export namespace Shape {
    export interface Triangle extends SeedApi.Triangle {
        type: "triangle";
    }

    export interface Square extends SeedApi.Square {
        type: "square";
    }

    export interface Circle extends SeedApi.Circle {
        type: "circle";
    }
}
