/**
 * This file was auto-generated by Fern from our API Definition.
 */
export class FernTestApiTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, FernTestApiTimeoutError.prototype);
    }
}
