# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from .country import CountryParams


class AccountParams(typing_extensions.TypedDict):
    address_type: typing.Literal["country"]
    name: str
    is_open: bool
    country: CountryParams
