# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata
from .account import AccountParams


class AccountListParams(typing_extensions.TypedDict):
    accounts: typing.Sequence[AccountParams]
    total_accounts: typing_extensions.Annotated[int, FieldMetadata(alias="totalAccounts")]
