# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions
from ...core.serialization import FieldMetadata


class AddressParams(typing_extensions.TypedDict):
    line_1: typing_extensions.Annotated[str, FieldMetadata(alias="line1")]
    line_2: typing_extensions.NotRequired[typing_extensions.Annotated[str, FieldMetadata(alias="line2")]]
    city: str
    state: str
    zip: str
    country: typing.Literal["USA"]
