# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import typing_extensions


class ExtensiveParams(typing_extensions.TypedDict):
    name: str
    creation_date: dt.date
    creation_time: dt.datetime
    nullable_string: typing.Optional[str]
    optional_nullable_string: typing_extensions.NotRequired[typing.Optional[str]]
