# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions


class ProjectParams(typing_extensions.TypedDict):
    is_open: typing.Literal[False]
    name: str
