# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions


class Shape_TriangleParams(typing_extensions.TypedDict):
    type: typing.Literal["triangle"]
    a: float
    b: float
    c: float


class Shape_SquareParams(typing_extensions.TypedDict):
    type: typing.Literal["square"]
    length: float


class Shape_CircleParams(typing_extensions.TypedDict):
    type: typing.Literal["circle"]
    radius: float


ShapeParams = typing.Union[Shape_TriangleParams, Shape_SquareParams, Shape_CircleParams]
