/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as FernTestApi from "../../../index.mjs";
export type Shape = FernTestApi.Shape.Triangle | FernTestApi.Shape.Square | FernTestApi.Shape.Circle;
export declare namespace Shape {
    interface Triangle extends FernTestApi.Triangle {
        type: "triangle";
    }
    interface Square extends FernTestApi.Square {
        type: "square";
    }
    interface Circle extends FernTestApi.Circle {
        type: "circle";
    }
}
