service:
  auth: false
  base-path: /
  endpoints:
    simple:
      path: "/snippet"
      method: POST

    downloadFile:
      path: "/download-file"
      method: POST
      response: file

    uploadFile:
      display-name: Upload file
      method: POST
      path: "/upload-file"
      request:
        body: bytes
        content-type: application/octet-stream
      response:
        type: string