service:
  auth: false
  base-path: /
  endpoints:
    simple:
      path: "/snippet"
      method: POST

    downloadFile:
      path: "/download-file"
      method: POST
      response: file

    uploadFile:
      display-name: Upload file
      method: POST
      path: "/upload-file"
      request:
        body: bytes
        content-type: application/octet-stream
      response:
        type: string

    uploadSingleDocument:
      path: /upload-single-document
      method: POST
      request:
        name: UploadSingleDocument
        body:
          properties:
            documentFile: file

    uploadListOfDocuments:
      path: /upload-list-of-documents
      method: POST
      request:
        name: UploadListOfDocuments
        body:
          properties:
            documentFile1: file
            documentFile2: file
            documentFiles: list<file>

    uploadMultipleDocumentsAndFields:
      path: /upload-multiple-documents-and-fields
      method: POST
      request:
        name: UploadMultipleDocumentsAndFields
        body:
          properties:
            documentFile1: file
            documentFile2: file
            documentFiles: list<file>
            someString: string
            someInteger: integer
            someBoolean: boolean
